  __          __        __  ___             
 |__)  _\/_  |__) |  | /__`  |   ____\/_  | 
 |      /\   |  \ \__/ .__/  |       /\   | 


Verification of 6 items...
error: [Prusti: unsupported feature] cast statements that create loans are not supported
  --> panic_files/parse_ip/parse_ip.rs:57:23
   |
57 |         _ => println!("{} not a valid address", s),
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^

error: [Prusti: unsupported feature] cast statements that create loans are not supported
  --> panic_files/parse_ip/parse_ip.rs:62:5
   |
62 | /     [
63 | |         "127.0.0.1",
64 | |         "127.0.0.1:80",
65 | |         "::1",
...  |
68 | |         "[2605:2700:0:3::4713:93e3]:80",
69 | |     ]
   | |_____^

error: [Prusti: unsupported feature] cast statements that create loans are not supported
  --> panic_files/parse_ip/parse_ip.rs:30:17
   |
30 |                 "address: {}, port: N/A, hex: {:x} (IPv{}) ",
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Positionless(Unsupported("memory equality between arrays is unsupported"))', prusti-viper/src/encoder/memory_eq_encoder.rs:250:23
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/core/src/result.rs:1355:5
   3: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   4: prusti_viper::encoder::memory_eq_encoder::MemoryEqEncoder::encode_memory_eq_func_app
   5: prusti_viper::encoder::encoder::Encoder::encode_memory_eq_func_app
   6: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_assign_operand
   7: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_statement
   8: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_statement_at
   9: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode_blocks_group
  10: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::encode
  11: prusti_viper::encoder::encoder::Encoder::encode_procedure
  12: prusti_viper::encoder::encoder::Encoder::process_encoding_queue
  13: prusti_viper::verifier::Verifier::verify
  14: prusti_driver::verifier::verify
  15: <prusti_driver::callbacks::PrustiCompilerCalls as rustc_driver::Callbacks>::after_analysis
  16: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  17: rustc_span::with_source_map
  18: rustc_interface::interface::create_compiler_and_run
  19: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: Prusti or the compiler unexpectedly panicked. This is a bug.

note: We would appreciate a bug report: https://github.com/viperproject/prusti-dev/issues/new

note: Prusti version: commit e8a9345e 2021-05-19 12:46:05 UTC, built on 2021-05-27 13:44:30 UTC

query stack during panic:
end of query stack
error: aborting due to 3 previous errors

