  __          __        __  ___             
 |__)  _\/_  |__) |  | /__`  |   ____\/_  | 
 |      /\   |  \ \__/ .__/  |       /\   | 


Verification of 4 items...
error: [Prusti: unsupported feature] cast statements that create loans are not supported
  --> panic_files/chat_server/chat_server.rs:19:30
   |
19 |             writeln!(stream, "{}", message)?;
   |                              ^^^^

error: [Prusti: unsupported feature] cast statements that create loans are not supported
  --> panic_files/chat_server/chat_server.rs:30:14
   |
30 |     println!("Accepting connections on {}", listener.local_addr()?.port());
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: [Prusti: unsupported feature] the encoding of this reference copy has not been implemented
  --> panic_files/chat_server/chat_server.rs:94:38
   |
94 |     let listener = TcpListener::bind(("localhost", 7000)).unwrap();
   |                                      ^^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at 'not implemented: ty=Closure(DefId(0:33 ~ chat_server[317d]::chat_loop::{closure#0}), [i32, extern "rust-call" fn(()) -> std::result::Result<(), std::io::Error>, (std::net::TcpStream, std::sync::Arc<std::sync::RwLock<std::collections::HashMap<std::string::String, std::net::TcpStream>>>)])', analysis/src/abstract_domains/place_utils.rs:81:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/core/src/panicking.rs:92:14
   2: analysis::abstract_domains::place_utils::expand_one_level
   3: analysis::abstract_domains::place_utils::expand
   4: analysis::abstract_domains::definitely_initialized::DefinitelyInitializedState::set_place_uninitialised
   5: <analysis::abstract_domains::definitely_initialized::DefinitelyInitializedState as analysis::abstract_state::AbstractState>::apply_statement_effect
   6: analysis::analyzer::Analyzer::run_fwd_analysis
   7: prusti_interface::environment::mir_analyses::initialization::compute_definitely_initialized
   8: prusti_viper::encoder::initialisation::InitInfo::new
   9: prusti_viper::encoder::procedure_encoder::ProcedureEncoder::new
  10: prusti_viper::encoder::encoder::Encoder::encode_procedure
  11: prusti_viper::encoder::encoder::Encoder::process_encoding_queue
  12: prusti_viper::verifier::Verifier::verify
  13: prusti_driver::verifier::verify
  14: <prusti_driver::callbacks::PrustiCompilerCalls as rustc_driver::Callbacks>::after_analysis
  15: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  16: rustc_span::with_source_map
  17: rustc_interface::interface::create_compiler_and_run
  18: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: Prusti or the compiler unexpectedly panicked. This is a bug.

note: We would appreciate a bug report: https://github.com/viperproject/prusti-dev/issues/new

note: Prusti version: commit e8a9345e 2021-05-19 12:46:05 UTC, built on 2021-05-27 13:44:30 UTC

query stack during panic:
end of query stack
error: aborting due to 3 previous errors

